name: 'medical_warehouse'
version: '1.0.0'
config-version: 2

profile: 'medical_warehouse'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
analysis-paths: ["analyses"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  medical_warehouse:
    materialized: table
    
    staging:
      +schema: staging
      +materialized: view
      
    marts:
      +schema: marts
      +materialized: table

seeds:
  medical_warehouse:
    +schema: seeds
    +materialized: table

vars:
  raw_schema: raw
  staging_schema: staging
  marts_schema: marts