medical_warehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', 5432) | as_number }}"
      user: "{{ env_var('POSTGRES_USER', 'postgres') }}"
      pass: "{{ env_var('POSTGRES_PASSWORD', 'postgres') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'telegram_warehouse') }}"
      schema: "{{ env_var('DBT_SCHEMA', 'dbt') }}"
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
      retries: 3